site_name: S2D01 Manual
site_url: https://s2d01.github.io/s2d01-docs-z9n4x1c/
docs_dir: docs

theme:
  name: material
  # language: it   # lo gestisce Langly
  palette:
    scheme: slate
    primary: blue
    accent: cyan
  custom_dir: overrides

plugins:
  - search
  - git-revision-date-localized:
      type: date
      locale: it
      timezone: Europe/Rome
      fallback_to_build_date: true


